from prometheus_client import Counter, Gauge, Histogram

sim_requests = Counter("sim_requests_total", "Simulator requests", ["endpoint", "status"])
sim_duration = Histogram("sim_request_duration_seconds", "Simulator latency", ["endpoint"])
sim_up = Gauge("sim_up", "Fresh validated simulator REST reads")
circuit = Gauge("sim_circuit_state", "Circuit open")
stream = Gauge("sim_stream_connected", "SSE connected")
age = Gauge("state_age_seconds", "Last good snapshot age")
stale = Gauge("state_stale", "State not safe for execution")
mode = Gauge("system_mode", "0 normal, 1 degraded, 2 recovering")
cycle = Histogram("decision_cycle_seconds", "Intelligence cycle seconds")
http_duration = Histogram("http_request_duration_seconds", "API latency", ["handler", "method"])
http_requests = Counter("http_requests_total", "API requests", ["handler", "method", "status"])
confidence = Histogram("recommendation_confidence", "Heuristic confidence")
recommendations = Counter("recommendations_total", "Recommendation changes", ["status"])
executions = Counter("decisions_executed_total", "Accepted shipments", ["mode"])
fallback = Gauge("fallback_active", "Local fallback in use", ["component"])
fallback_count = Counter("fallback_activations_total", "Fallback activations", ["component"])
review = Counter("human_review_requests_total", "Consequential plans queued")
alerts = Counter("shortage_alerts_total", "New alerts", ["severity"])
inventory = Gauge("station_inventory_liters", "Station fuel", ["station", "fuel"])
risk = Gauge("station_stockout_risk", "Estimated stockout risk", ["station", "fuel"])
cover = Gauge("station_hours_to_stockout", "Hours to stockout; -1 beyond horizon", ["station", "fuel"])
depot_inventory = Gauge("depot_inventory_liters", "Depot fuel", ["depot", "fuel"])
service = Gauge("sim_service_level", "Simulator service level")
unmet = Gauge("sim_unmet_liters", "Cumulative unmet fuel")
failures = Gauge("sim_allocation_failures", "Simulator failed allocations")
forecast_mae = Gauge("forecast_mae", "One-step demand mean absolute error", ["model"])
